package net.yuma14.mc.lib_json_model.api.v1;

import net.minecraft.block.Block;
import net.minecraft.client.renderer.RenderBlocks;
import net.minecraft.util.AxisAlignedBB;
import net.minecraft.world.IBlockAccess;
import net.yuma14.mc.lib_json_model.api.v1.math.BCS;
import net.yuma14.mc.lib_json_model.api.v1.math.Cuboid;

import java.util.List;
import java.util.stream.Stream;

/**
 * Block model generated by compiling a JSON model
 */
public interface IBlockModel {
    /**
     * List the AABBs for the collision detection
     * <p>
     * This method is supposed to be called from Block#addCollisionBoxesToList().
     * In that case, it should not be slow, as it will be called every tick
     * while an entity is touching the block.
     *
     * @param x
     * @param y
     * @param z
     * @param mask
     * @param list
     */
    void addCollisionBoxesToList(int x, int y, int z, AxisAlignedBB mask, @SuppressWarnings("rawtypes") List list);

    /**
     * all Cuboids that make up this model
     */
    Stream<Cuboid<BCS>> getCuboids();

    /**
     * Used to render models in inventory by classes that implement the ISimpleBlockRenderingHandler
     */
    void renderInventoryBlock();

    /**
     * Used to render models in the world by classes that implement the ISimpleBlockRenderingHandler
     *
     * @param world
     * @param x
     * @param y
     * @param z
     * @param block
     * @param renderer
     * @return true if something was drawn, false if nothing was drawn
     */
    boolean renderWorldBlock(IBlockAccess world, int x, int y, int z, Block block, RenderBlocks renderer);

    /**
     * Used to render models in the world by TileEntitySpecialRenderer
     */
    void renderTileEntity();
}
