package net.yuma14.mc.lib_json_model.api.v1;

import net.minecraft.block.Block;
import net.minecraft.client.renderer.RenderBlocks;
import net.minecraft.util.AxisAlignedBB;
import net.minecraft.world.IBlockAccess;

import java.util.List;

/**
 * Block model generated by compiling a JSON model
 */
public interface IBlockModel {
    /**
     * Add the AABBs representing the hit decision to the list.
     * <p>
     * This method is supposed to be called from Block#addCollisionBoxesToList().
     * In that case, it should not be slow, as it will be called every tick
     * while an entity is touching the block.
     *
     * @param x
     * @param y
     * @param z
     * @param mask
     * @param list
     */
    void addCollisionBoxesToList(int x, int y, int z, AxisAlignedBB mask, @SuppressWarnings("rawtypes") List list);

    // for ISimpleBlockRenderingHandler
    void renderInventoryBlock();

    // for ISimpleBlockRenderingHandler
    boolean renderWorldBlock(IBlockAccess world, int x, int y, int z, Block block, RenderBlocks renderer);

    // for TileEntitySpecialRenderer
    void renderTileEntity();
}
